<!doctype html>
  <html lang=en>
  <head>
      <meta charset='utf-8'>
      <link rel="stylesheet" type="text/css" href="styles.css">
      <link rel="stylesheet" type="text/css" href="nav-menu.css">
      <title>Assignment 03</title>
  </head>

  <body>
    <nav>
      <ul>
        <li> <a href="index.html"> Homepage </a></li>
        <li>  <a href="lihui.html"> Homepage </a></li>
        <li>  <a href="aliye.html"> Homepage </a></li>
        <li>  <a href="cassidy.html"> Homepage </a></li>
      </ul>
    </nav>