<!doctype html>
  <html lang=en>
  <head>
      <meta charset='utf-8'>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" type="text/css" href="css/styles.css">
      <link rel="stylesheet" type="text/css" href="css/nav-menu.css">
      <link href="https://fonts.googleapis.com/css?family=Shadows+Into+Light" rel="stylesheet">
      <title>Assignment 03</title>
  </head>

  <body>
    <nav>
      <ul>
        <li> <a href="index.php">Homepage</a></li>
        <li>  <a href="lihui.php">Lihui Guo</a></li>
        <li>  <a href="aliye.php">Aliye Gallagher</a></li>
        <li>  <a href="cassidy.php">Cassidy Clayton</a></li>
      </ul>
    </nav>

